# Generated by Django 5.2.17 on 2026-09-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='zone',
            name='next_shelf_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
