# Generated by Django 5.2.17 on 2026-09-05 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_use_feet_for_shop_dimensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('agent_reference', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_outlets', to='core.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MpesaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=14)),
                ('opened_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('closing_cash_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closing_float_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_sessions', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='mpesa.mpesaoutlet')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_cash', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_variance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_float', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_float', models.DecimalField(decimal_places=2, max_digits=14)),
                ('float_variance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_reconciliations_reviewed', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation', to='mpesa.mpesasession')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reference', models.CharField(max_length=60, unique=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('CUSTOMER_DEPOSIT', 'Customer Deposit'), ('CUSTOMER_WITHDRAWAL', 'Customer Withdrawal'), ('FLOAT_TOPUP', 'Float Topup'), ('CASH_REBALANCE', 'Cash Rebalance'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('float_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('customer_reference', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='POSTED', max_length=12)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='mpesa.mpesaoutlet')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='mpesa.mpesatransaction')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='mpesa.mpesasession')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'permissions': [('reverse_mpesa_transaction', 'Can reverse M-Pesa agency transactions')],
            },
        ),
        migrations.CreateModel(
            name='MpesaCommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('settlement_method', models.CharField(max_length=40)),
                ('recognized_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='mpesa.mpesaoutlet')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='nonnegative_mpesa_commission')],
            },
        ),
        migrations.AddConstraint(
            model_name='mpesasession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('outlet',), name='one_open_mpesa_session_per_outlet'),
        ),
        migrations.AddConstraint(
            model_name='mpesasession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_cash__gte', 0), ('opening_float__gte', 0)), name='nonnegative_mpesa_opening_balances'),
        ),
        migrations.AddConstraint(
            model_name='mpesatransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_mpesa_transaction_amount'),
        ),
    ]
