import { useEffect, useState } from "react";
import { Empty, ErrorState, Loading } from "../../components/States";
import { getMpesaDashboard, getMpesaOutlets, getMpesaTransactions, openMpesaSession, postMpesaTransaction, reconcileMpesaSession, reverseMpesaTransaction } from "./api";
import { MpesaDepositForm } from "./MpesaDepositForm";
import { MpesaWithdrawalForm } from "./MpesaWithdrawalForm";
import type { MpesaDashboard, MpesaOutlet, MpesaTransaction } from "./types";

export function MpesaDashboardPage() {
  const [dashboard, setDashboard] = useState<MpesaDashboard>(); const [outlets, setOutlets] = useState<MpesaOutlet[]>([]); const [transactions, setTransactions] = useState<MpesaTransaction[]>([]); const [error, setError] = useState("");
  const load = async () => { try { const [summary, outletRows, entries] = await Promise.all([getMpesaDashboard(), getMpesaOutlets(), getMpesaTransactions()]); setDashboard(summary); setOutlets(outletRows); setTransactions(entries); setError(""); } catch (err) { setError((err as Error).message); } };
  useEffect(() => { void load(); }, []); if (error) return <ErrorState message={error} retry={load} />; if (!dashboard) return <Loading />;
  const open = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await openMpesaSession({ outlet: form.get("outlet"), opening_cash: form.get("opening_cash"), opening_float: form.get("opening_float") }); await load(); };
  const rebalance = async (type: "FLOAT_TOPUP" | "CASH_REBALANCE") => { if (!dashboard.session) return; const value = window.prompt(type === "FLOAT_TOPUP" ? "Float top-up amount" : "Cash received during rebalance"); if (!value) return; await postMpesaTransaction({ session: dashboard.session.id, transaction_type: type, amount: value, provider_reference: window.prompt("Reference") || undefined, notes: window.prompt("Source / notes") || "", idempotency_key: crypto.randomUUID() }); await load(); };
  const close = async () => { if (!dashboard.session) return; const actualCash = window.prompt("Actual cash counted", dashboard.cash); const actualFloat = window.prompt("Actual electronic float", dashboard.float); if (actualCash === null || actualFloat === null) return; const reason = (+actualCash !== +dashboard.cash || +actualFloat !== +dashboard.float) ? window.prompt("Variance reason (required)", "") : ""; await reconcileMpesaSession(dashboard.session.id, { actual_cash: actualCash, actual_float: actualFloat, reason }); await load(); };
  return <><span className="eyebrow">Separate agency ledger</span><h1>M-Pesa Agent</h1><p className="privacyNotice">Agency deposits and withdrawals move cash and electronic float. Their principal is never sales revenue.</p>
    <div className="metrics"><article><span>Current cash</span><strong>KSh {dashboard.cash}</strong></article><article><span>Current float</span><strong>KSh {dashboard.float}</strong></article><article><span>Today's deposits</span><strong>KSh {dashboard.deposits}</strong></article><article><span>Today's withdrawals</span><strong>KSh {dashboard.withdrawals}</strong></article><article><span>Transactions</span><strong>{dashboard.transaction_count}</strong></article><article><span>Commission</span><strong>KSh {dashboard.commission}</strong></article></div>
    {!dashboard.session ? <form className="formCard shiftForm" onSubmit={(event) => void open(event)}><h2>Open M-Pesa shift</h2>{!outlets.length && <p>No active outlet exists. Ask the Owner to configure one in Django Admin.</p>}<label>Outlet<select name="outlet" required>{outlets.filter((outlet) => outlet.active).map((outlet) => <option key={outlet.id} value={outlet.id}>{outlet.display_name}</option>)}</select></label><label>Opening cash<input name="opening_cash" type="number" min="0" step="0.01" required /></label><label>Opening float<input name="opening_float" type="number" min="0" step="0.01" required /></label><button disabled={!outlets.length}>Open shift</button></form> : <><div className="deskActions"><button onClick={() => void rebalance("FLOAT_TOPUP")}>Float top-up</button><button onClick={() => void rebalance("CASH_REBALANCE")}>Cash rebalance</button><button className="secondary" onClick={() => void close()}>Close & reconcile shift</button></div><div className="deskGrid"><MpesaDepositForm sessionId={dashboard.session.id} onPosted={load} /><MpesaWithdrawalForm sessionId={dashboard.session.id} availableCash={dashboard.cash} onPosted={load} /></div></>}
    <section><h2>Agency transactions</h2>{!transactions.length ? <Empty>No M-Pesa agency transactions.</Empty> : <div className="table ledgerTable"><div><b>Reference</b><b>Type</b><b>Amount</b><b>Cash effect</b><b>Float effect</b><b>Action</b></div>{transactions.slice(0, 30).map((entry) => <div key={entry.id}><span>{entry.provider_reference || entry.internal_reference}</span><span>{entry.transaction_type.replaceAll("_", " ")}</span><span>KSh {entry.amount}</span><span>{entry.cash_delta}</span><span>{entry.float_delta}</span><span>{entry.transaction_type !== "REVERSAL" && !entry.reversal_of && <button className="danger" onClick={() => { const reason = window.prompt("Reversal reason"); if (reason) void reverseMpesaTransaction(entry.id, reason).then(load); }}>Reverse</button>}</span></div>)}</div>}</section></>;
}
