from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone
from apps.catalog.models import ProductVariant
from apps.core.models import TimeStamped
class Cart(TimeStamped):
    session_key=models.CharField(max_length=40,blank=True,db_index=True); customer=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,related_name="carts",on_delete=models.CASCADE); active=models.BooleanField(default=True)
    class Meta: constraints=[models.UniqueConstraint(fields=["customer"],condition=Q(active=True,customer__isnull=False),name="one_active_customer_cart")]
class CartItem(TimeStamped):
    cart=models.ForeignKey(Cart,related_name="items",on_delete=models.CASCADE); variant=models.ForeignKey(ProductVariant,on_delete=models.CASCADE); quantity=models.DecimalField(max_digits=14,decimal_places=3)
    class Meta: constraints=[models.UniqueConstraint(fields=["cart","variant"],name="unique_cart_variant"),models.CheckConstraint(condition=Q(quantity__gt=0),name="positive_cart_quantity")]
class Order(TimeStamped):
    STATUSES=[(x,x.replace("_"," ").title()) for x in ["PENDING","AWAITING_PAYMENT","PAID","PROCESSING","READY_FOR_PICKUP","OUT_FOR_DELIVERY","COMPLETED","CANCELLED","REFUNDED"]]; PAYMENT_STATUSES=[(x,x.title()) for x in ["PENDING","MANUAL_REVIEW","PAID","FAILED","REFUNDED"]]; FULFILLMENT=[(x,x.replace("_"," ").title()) for x in ["UNFULFILLED","PROCESSING","READY_FOR_PICKUP","OUT_FOR_DELIVERY","COMPLETED","CANCELLED"]]
    number=models.CharField(max_length=40,unique=True); customer=models.ForeignKey(settings.AUTH_USER_MODEL,related_name="orders",on_delete=models.PROTECT); status=models.CharField(max_length=30,choices=STATUSES,default="PENDING"); payment_status=models.CharField(max_length=20,choices=PAYMENT_STATUSES,default="PENDING"); fulfillment_status=models.CharField(max_length=30,choices=FULFILLMENT,default="UNFULFILLED"); fulfillment_method=models.CharField(max_length=20,choices=[("PICKUP","Pickup"),("DELIVERY","Delivery")],default="PICKUP"); address=models.ForeignKey("accounts.CustomerAddress",null=True,blank=True,on_delete=models.PROTECT); subtotal=models.DecimalField(max_digits=14,decimal_places=2); discount=models.DecimalField(max_digits=14,decimal_places=2,default=0); total=models.DecimalField(max_digits=14,decimal_places=2); notes=models.TextField(blank=True); completed_at=models.DateTimeField(null=True,blank=True)
class OrderItem(models.Model):
    order=models.ForeignKey(Order,related_name="items",on_delete=models.PROTECT); variant=models.ForeignKey(ProductVariant,on_delete=models.PROTECT); product_name=models.CharField(max_length=220); variant_name=models.CharField(max_length=120); sku=models.CharField(max_length=64); quantity=models.DecimalField(max_digits=14,decimal_places=3); unit_price=models.DecimalField(max_digits=14,decimal_places=2); reservation=models.OneToOneField("inventory.Reservation",null=True,blank=True,related_name="order_item",on_delete=models.PROTECT)
class OrderStatusHistory(models.Model):
    order=models.ForeignKey(Order,related_name="history",on_delete=models.CASCADE); status=models.CharField(max_length=30); note=models.CharField(max_length=255,blank=True); changed_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL); created_at=models.DateTimeField(auto_now_add=True)
class Sale(TimeStamped):
    POS="POS"; ONLINE="ONLINE"; CYBER="CYBER"
    number=models.CharField(max_length=40,unique=True); channel=models.CharField(max_length=10,choices=[(POS,"POS"),(ONLINE,"Online"),(CYBER,"Cyber")]); status=models.CharField(max_length=20,default="COMPLETED"); order=models.OneToOneField(Order,null=True,blank=True,related_name="sale",on_delete=models.PROTECT); customer=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True,on_delete=models.SET_NULL); subtotal=models.DecimalField(max_digits=14,decimal_places=2,default=0); discount=models.DecimalField(max_digits=14,decimal_places=2,default=0); total=models.DecimalField(max_digits=14,decimal_places=2,default=0); cogs=models.DecimalField(max_digits=14,decimal_places=2,default=0); gross_profit=models.DecimalField(max_digits=14,decimal_places=2,default=0); created_by=models.ForeignKey(settings.AUTH_USER_MODEL,null=True,on_delete=models.SET_NULL,related_name="sales_created")
class SaleItem(models.Model):
    sale=models.ForeignKey(Sale,related_name="items",on_delete=models.PROTECT); variant=models.ForeignKey(ProductVariant,on_delete=models.PROTECT); quantity=models.DecimalField(max_digits=14,decimal_places=3); unit_price=models.DecimalField(max_digits=14,decimal_places=2); discount=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal("0")); cost=models.DecimalField(max_digits=14,decimal_places=2,default=Decimal("0"))
class SaleAllocation(models.Model):
    item=models.ForeignKey(SaleItem,related_name="allocations",on_delete=models.PROTECT); lot=models.ForeignKey("inventory.StockLot",on_delete=models.PROTECT); shelf=models.ForeignKey("inventory.Shelf",on_delete=models.PROTECT); quantity=models.DecimalField(max_digits=14,decimal_places=3); unit_cost=models.DecimalField(max_digits=14,decimal_places=2)
class Payment(models.Model):
    STATUSES=[(x,x.replace("_"," ").title()) for x in ["PENDING","MANUAL_REVIEW","COMPLETED","FAILED","REFUNDED"]]
    sale=models.ForeignKey(Sale,null=True,blank=True,related_name="payments",on_delete=models.PROTECT); order=models.ForeignKey(Order,null=True,blank=True,related_name="payments",on_delete=models.PROTECT); method=models.CharField(max_length=20,choices=[(x,x.title()) for x in ["CASH","MPESA","BANK","OTHER","CASH_ON_PICKUP"]]); amount=models.DecimalField(max_digits=14,decimal_places=2); reference=models.CharField(max_length=100,blank=True); status=models.CharField(max_length=20,choices=STATUSES,default="PENDING"); idempotency_key=models.CharField(max_length=100,unique=True); provider_transaction_id=models.CharField(max_length=120,null=True,blank=True,unique=True); created_at=models.DateTimeField(default=timezone.now,editable=False); updated_at=models.DateTimeField(default=timezone.now)
    class Meta: constraints=[models.CheckConstraint(condition=Q(sale__isnull=False)|Q(order__isnull=False),name="payment_has_subject")]
