# Generated by Django 5.2.17 on 2026-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_orderitem_orderstatushistory_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('POS', 'POS'), ('ONLINE', 'Online'), ('CYBER', 'Cyber')], max_length=10),
        ),
    ]
