# Generated by Django 5.2.17 on 2026-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_orderable',
            field=models.BooleanField(default=True),
        ),
    ]
