# Generated by Django 5.2.17 on 2026-09-02 20:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('reference', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('allocations', models.JSONField(default=list)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=160)),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sort_order', models.IntegerField(default=0)),
                ('capacity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelves_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.shelf')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelves_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShelfHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='inventory.shelf')),
            ],
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=80)),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('supplier_name', models.CharField(blank=True, max_length=180)),
                ('received_at', models.DateTimeField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('reserved', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.shelf')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('movement_type', models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALE', 'Sale'), ('ONLINE_ORDER', 'Online Order'), ('TRANSFER', 'Transfer'), ('CUSTOMER_RETURN', 'Customer Return'), ('SUPPLIER_RETURN', 'Supplier Return'), ('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('STOCKTAKE_ADJUSTMENT', 'Stocktake Adjustment'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('ORDER_RESERVATION', 'Order Reservation'), ('RESERVATION_RELEASE', 'Reservation Release'), ('OTHER', 'Other')], max_length=30)),
                ('reference', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='inventory.shelf')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='inventory.shelf')),
                ('lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('width', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.store')),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelves', to='inventory.zone'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0), ('remaining_quantity__gte', 0)), name='nonnegative_lot'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('lot', 'shelf'), name='unique_lot_shelf'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('reserved__gte', 0), ('reserved__lte', models.F('quantity'))), name='valid_stock_balance'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='unique_zone_code'),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('zone', 'code'), name='unique_shelf_code_zone'),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0), ('height__gt', 0)), name='positive_shelf_dimensions'),
        ),
    ]
