# Generated by Django 5.2.17 on 2026-09-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
        ('inventory', '0002_reservation_status_zone_next_shelf_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_number', models.PositiveIntegerField()),
                ('y_position', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.AddField(
            model_name='shelf',
            name='physical_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='shelf',
            name='position_in_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='code',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveBigIntegerField()),
                ('event', models.CharField(max_length=40)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shelves', to='inventory.shelflevel'),
        ),
        migrations.CreateModel(
            name='ShelfStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=160)),
                ('x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('number_of_levels', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stacks_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stacks_updated', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stacks', to='inventory.zone')),
            ],
        ),
        migrations.AddField(
            model_name='shelflevel',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='inventory.shelfstack'),
        ),
        migrations.CreateModel(
            name='VariantPreferredLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preferred_variants', to='inventory.shelf')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_location', to='catalog.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='shelfstack',
            constraint=models.CheckConstraint(condition=models.Q(('width__gt', 0), ('height__gt', 0), ('depth__gt', 0), ('number_of_levels__gt', 0)), name='positive_stack_dimensions'),
        ),
        migrations.AddConstraint(
            model_name='shelflevel',
            constraint=models.UniqueConstraint(fields=('stack', 'level_number'), name='unique_stack_level'),
        ),
        migrations.AddConstraint(
            model_name='shelflevel',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0), ('level_number__gt', 0)), name='positive_level_geometry'),
        ),
    ]
