# Generated by Django 5.2.17 on 2026-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_shelflevel_shelf_physical_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALE', 'Sale'), ('ONLINE_ORDER', 'Online Order'), ('CYBER_CONSUMPTION', 'Cyber Consumption'), ('TRANSFER', 'Transfer'), ('CUSTOMER_RETURN', 'Customer Return'), ('SUPPLIER_RETURN', 'Supplier Return'), ('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('STOCKTAKE_ADJUSTMENT', 'Stocktake Adjustment'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('ORDER_RESERVATION', 'Order Reservation'), ('RESERVATION_RELEASE', 'Reservation Release'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
