import {useEffect,useState} from "react"; import {Link,NavLink,Route,Routes} from "react-router-dom"; import {LayoutDashboard,Map,ShoppingBag,ShoppingCart,SunMoon} from "lucide-react";
type Theme="system"|"light"|"dark"; type Shelf={id:number;code:string;display_name:string;x:string;y:string;width:string;height:string;total_quantity:string}; type Zone={id:number;code:string;name:string;width:string;height:string;shelves:Shelf[]};
function ThemePicker(){const [theme,setTheme]=useState<Theme>(()=>(localStorage.getItem("theme") as Theme)||"system"); useEffect(()=>{const media=matchMedia("(prefers-color-scheme: dark)"); const apply=()=>{document.documentElement.dataset.theme=theme==="system"?(media.matches?"dark":"light"):theme}; apply(); media.addEventListener("change",apply); localStorage.setItem("theme",theme); return()=>media.removeEventListener("change",apply)},[theme]); return <label className="theme"><SunMoon size={17}/><span className="sr">Theme</span><select value={theme} onChange={e=>setTheme(e.target.value as Theme)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label>}
function Store(){return <><section className="hero"><div><span className="eyebrow">Technology for everyday life</span><h1>Your trusted digital point.</h1><p>Mobile accessories, electrical essentials, computing products, and professional cyber services.</p><Link className="button" to="/shop">Shop products</Link></div><div className="heroCard"><ShoppingBag size={50}/><b>Quality products.<br/>Local service.</b><span>Prices in Kenyan Shillings</span></div></section><h2>Popular departments</h2><div className="cards">{["Phone accessories","Cables & chargers","Computer accessories","Printing & cyber services"].map(x=><article key={x}><h3>{x}</h3><p>Browse reliable essentials selected for LinTech customers.</p></article>)}</div></>}
function Shop(){return <main><h1>Shop</h1><p className="muted">Products load from the unified physical-store inventory.</p><div className="empty">The catalog is ready. Add active products from the administration area.</div></main>}
function Dashboard(){return <AdminShell><h1>Dashboard</h1><div className="metrics">{["Revenue today","Gross profit","Stock cost value","Low stock"].map((x,i)=><article key={x}><span>{x}</span><strong>{i===3?"0":i===0?"KSh 0.00":"—"}</strong></article>)}</div><section className="panel"><h2>Business overview</h2><p className="muted">Live metrics will appear as sales, expenses and inventory movements are recorded.</p></section></AdminShell>}
function DigitalShop(){const [zones,setZones]=useState<Zone[]>([]); const [selected,setSelected]=useState<number>(); useEffect(()=>{fetch("/api/v1/locations/zones/",{credentials:"include"}).then(r=>r.ok?r.json():[]).then(x=>{const rows=x.results||x;setZones(rows);setSelected(rows[0]?.id)})},[]); const z=zones.find(x=>x.id===selected); return <AdminShell><div className="heading"><div><span className="eyebrow">Digital twin</span><h1>Shop Layout</h1></div></div><div className="tabs">{zones.map(x=><button className={selected===x.id?"active":""} onClick={()=>setSelected(x.id)} key={x.id}>{x.name}</button>)}</div>{z?<section className="wall" style={{aspectRatio:`${z.width}/${z.height}`}} aria-label={z.name}>{z.shelves.map(s=><button className="shelf" key={s.id} style={{left:`${+s.x/+z.width*100}%`,top:`${+s.y/+z.height*100}%`,width:`${+s.width/+z.width*100}%`,height:`${+s.height/+z.height*100}%`}}><b>{s.code}</b><span>{s.display_name}</span><small>{s.total_quantity} units</small></button>)}{!z.shelves.length&&<div className="wallEmpty"><Map/><h2>Configure {z.name}</h2><p>Add shelves with their real position and unequal dimensions.</p></div>}</section>:<div className="empty">Sign in to configure the physical shop.</div>}</AdminShell>}
function AdminShell({children}:{children:React.ReactNode}){return <div className="admin"><aside><Link className="brand" to="/">LinTech<span>Digital Point</span></Link><nav><NavLink to="/admin-app/dashboard"><LayoutDashboard/>Dashboard</NavLink><NavLink to="/admin-app/pos"><ShoppingCart/>Point of Sale</NavLink><NavLink to="/admin-app/digital-shop"><Map/>Digital Shop</NavLink><NavLink to="/admin-app/products"><ShoppingBag/>Products</NavLink></nav></aside><main>{children}</main></div>}
function Placeholder({title}:{title:string}){return <AdminShell><h1>{title}</h1><div className="empty">This workspace is ready for authorized operations.</div></AdminShell>}
export default function App(){return <><header><Link className="brand" to="/">LinTech<span>Digital Point</span></Link><nav><NavLink to="/">Home</NavLink><NavLink to="/shop">Shop</NavLink><NavLink to="/admin-app/dashboard">Admin</NavLink></nav><ThemePicker/></header><Routes><Route path="/" element={<main><Store/></main>}/><Route path="/shop" element={<Shop/>}/><Route path="/admin-app/dashboard" element={<Dashboard/>}/><Route path="/admin-app/digital-shop" element={<DigitalShop/>}/><Route path="/admin-app/pos" element={<Placeholder title="Point of Sale"/>}/><Route path="/admin-app/products" element={<Placeholder title="Products"/>}/></Routes></>}
