# Generated by Django 5.2.17 on 2026-09-05 13:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_online_orderable'),
        ('commerce', '0003_alter_sale_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('walk_in_customer_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('WAITING_CUSTOMER', 'Waiting Customer'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyber_jobs', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyber_jobs_operated', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cyber_job', to='commerce.sale')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('complete_cyber_job', 'Can complete and take payment for Cyber jobs')],
            },
        ),
        migrations.CreateModel(
            name='CyberServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_unit', models.CharField(choices=[('PER_PAGE', 'Per Page'), ('PER_COPY', 'Per Copy'), ('PER_SHEET', 'Per Sheet'), ('PER_DOCUMENT', 'Per Document'), ('PER_HOUR', 'Per Hour'), ('PER_ITEM', 'Per Item'), ('FIXED', 'Fixed')], max_length=20)),
                ('default_turnaround', models.DurationField(blank=True, null=True)),
                ('requires_job', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('publicly_advertised', models.BooleanField(default=True)),
                ('online_orderable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cyber_profile', to='catalog.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CyberJobLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=220)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('billing_unit', models.CharField(choices=[('PER_PAGE', 'Per Page'), ('PER_COPY', 'Per Copy'), ('PER_SHEET', 'Per Sheet'), ('PER_DOCUMENT', 'Per Document'), ('PER_HOUR', 'Per Hour'), ('PER_ITEM', 'Per Item'), ('FIXED', 'Fixed')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('service_details', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='cyber.cyberjob')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_cyber_line_quantity')],
            },
        ),
        migrations.CreateModel(
            name='ServiceMaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_per_service_unit', models.DecimalField(decimal_places=3, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('material_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_material_uses', to='catalog.productvariant')),
                ('service_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requirements', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service_variant', 'material_variant'), name='unique_cyber_material_requirement'), models.CheckConstraint(condition=models.Q(('quantity_per_service_unit__gt', 0)), name='positive_cyber_material_quantity')],
            },
        ),
    ]
